name: Emoji Manager Workflow

on:
  workflow_dispatch:
  push:
    paths:
      - 'emojis/**'
      - '.github/workflows/emoji-manager.yml'

jobs:
  emoji-manager-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install --upgrade pip

      - name: Run emoji manager
        run: python emojis/emoji_manager.py emojis
