name: Emoji Manage

on:
  push:
    paths:
      - 'emojis/**'
      - '.github/workflows/emoji_manage.yml'

jobs:
  emoji_manage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install --upgrade pip
      - name: Run emoji manager
        run: python emojis/emoji_manager.py --input emojis
