name: 自动替换Emoji

on:
  workflow_dispatch:   # 允许手动触发
  push:
    paths:
      - 'emojis/*.json'
      - 'emojis/emojis.py'

jobs:
  emoji-replace:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置Python环境
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 安装依赖
        run: |
          pip install --upgrade pip

      - name: 运行Emoji自动替换
        run: |
          cd emojis
          python emojis.py

      - name: 提交更新（如有变更）
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add output/*.json
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "自动更新: 替换emojis"
            git push
          fi
