name: 自动替换Emoji

on:
  workflow_dispatch:   # 允许手动触发
  push:
    paths:
      - 'emojis/*.json'
      - 'emojis/emojis.py'

jobs:
  emoji-replace:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置Python环境
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 安装依赖
        run: |
          pip install --upgrade pip

      - name: 运行Emoji自动替换
        run: |
          cd emojis
          python emojis.py

      - name: 查找所有变更的output文件
        id: changed
        run: |
          cd emojis/output
          if [ -f .changed_files.txt ]; then
            cat .changed_files.txt
            echo "files<<EOF" >> $GITHUB_OUTPUT
            cat .changed_files.txt >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          else
            echo "files=" >> $GITHUB_OUTPUT
          fi

      - name: 提交更新（如有变更）
        if: steps.changed.outputs.files != ''
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          while read fn; do
            git add "$fn"
          done < emojis/output/.changed_files.txt
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "自动更新: 替换emojis"
            git push
          fi
