# .github/workflows/emoji_replace.yml

name: Emoji 替换管理器

on:
  push:
    paths:
      - 'emojis/**'
      - '.github/workflows/emoji_replace.yml'
  workflow_dispatch:  # 手动触发

jobs:
  run-emoji-processor:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 设置 Python 环境
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: 安装依赖
        run: pip install requests

      - name: 执行 Emoji 替换处理
        run: python emojis/process_emojis.py --input_dir=. --output_dir=emojis/output

      - name: 上传结果文件
        uses: actions/upload-artifact@v4
        with:
          name: processed-emojis
          path: emojis/output/
